### PR TITLE
feat: allow schemas to accept multiple glob patterns

### PR DESCRIPTION
**Pull request by nawilson**
This feature is to allow the CLI to support multiple globs for the --schemas flag.

```
Usage

  $ prisma-import [flags/options]
  $ prisma-import -s "glob/pattern/for/schemas" -o path/to/output/schema.prisma
  $ prisma-import -s "glob/pattern/for/schemas" -s "other/glob/pattern/for/schemas" -o path/to/output/schema.prisma
```

### CODE REVIEW

**Comment by ajmnz** [comment]
Looks good @nawilson, thank you!

I went back to using `arg` from `@prisma/internal` as it already supported array parameters and this way we can still keep support for older Node.js engines. Also cleaned up typings a bit in order to not rely on Type Assertions so heavily.

**Comment by nawilson** [comment]
@ajmnz  With the revised code (using @prisma/internals) it no longer works as intended. The published code (v1.0.5) does not work with multiple --schemas flag

**Comment by ajmnz** [comment]
> @ajmnz With the revised code (using @prisma/internals) it no longer works as intended. The published code (v1.0.5) does not work with multiple --schemas flag

Could you provide a reproduction? Tried it before merging and was working great. Thanks!

**Comment by nawilson** [comment]
Never mind. My mistake. I forgot to put double quotes around the glob.

**Pull request merged**
